-- Add `comment.body` — canonical PortableText representation of the
-- comment body. The legacy `comment.content` column is kept around as
-- a plain-text / markdown rollback snapshot (every save now writes
-- both columns: the editor produces PT, the server serialises it back
-- to markdown for `content`).
--
-- Existing rows ship with the JSONB default `'[]'::jsonb`; the
-- companion backfill script (`scripts/migrate-comments-to-pt.ts`)
-- converts the markdown stored in `content` into a PortableText body
-- and writes it to `body`. The script is idempotent so re-runs on
-- already-converted rows are no-ops.
ALTER TABLE "comment" ADD COLUMN IF NOT EXISTS "body" jsonb NOT NULL DEFAULT '[]'::jsonb;
