networks:
  astro:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: 127.0.0.1
services:
  database:
    container_name: astro-database
    image: postgres:17
    hostname: astro-database
    restart: always
    shm_size: 128mb
    volumes:
      - ./drizzle:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: astro
      POSTGRES_USER: astro
      POSTGRES_PASSWORD: '@str0!SecRets'
    networks:
      - astro
  cache:
    container_name: astro-cache
    image: redis:8
    hostname: astro-cache
    restart: always
    environment:
      REDIS_PASSWORD: '@str0!SecRets'
    command: /bin/sh -c 'redis-server --requirepass ${REDIS_PASSWORD}'
    networks:
      - astro
  astro:
    container_name: astro
    image: syhily/yufan.me
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 4321:4321
    depends_on:
      - database
      - cache
    networks:
      - astro
