// DOM-based popup helpers. We deliberately avoid `innerHTML` for any user
// controlled string (titles, names, messages, etc.) to keep the XSS surface
// near zero. Static SVG markup that we control ourselves is opted in via the
// `qrcodeSvg` parameter.

interface PopupOptions {
  /** Optional extra class added to the .nice-popup container (e.g. nice-popup-md). */
  sizeClass?: string
  /** Animate add/remove. Defaults to true. */
  animate?: boolean
}

export function createDialogShell(options: PopupOptions = {}): { popup: HTMLElement; content: HTMLElement } {
  const popup = document.createElement('div')
  popup.className = `nice-popup nice-popup-center ${options.sizeClass ?? 'nice-popup-sm'}`

  const overlay = document.createElement('div')
  overlay.className = 'nice-popup-overlay'

  const body = document.createElement('div')
  body.className = 'nice-popup-body'

  const close = document.createElement('div')
  close.className = 'nice-popup-close'
  const closeIcon = document.createElement('span')
  closeIcon.className = 'svg-white'
  close.appendChild(closeIcon)

  const content = document.createElement('div')
  content.className = 'nice-popup-content'

  body.appendChild(close)
  body.appendChild(content)
  popup.appendChild(overlay)
  popup.appendChild(body)

  return { popup, content }
}

export function showPopup(popup: HTMLElement): void {
  document.body.appendChild(popup)
  requestAnimationFrame(() => popup.classList.add('nice-popup-open'))
}

export function hidePopup(popup: HTMLElement | null): void {
  if (!popup) return
  popup.classList.remove('nice-popup-open')
  setTimeout(() => {
    if (!popup.classList.contains('nice-popup-open')) {
      popup.remove()
    }
  }, 300)
}

export function buildQrPopup(title: string, name: string, qrcodeSvg: string): HTMLElement {
  const { popup, content } = createDialogShell()

  const wrapper = document.createElement('div')
  wrapper.className = 'text-center'

  const heading = document.createElement('h6')
  heading.textContent = title

  const subtitle = document.createElement('p')
  subtitle.className = 'mt-1 mb-2'
  subtitle.textContent = name

  const qr = document.createElement('div')
  qr.className = 'qrcode d-flex justify-content-center align-items-center p-2'
  // qrcodeSvg is generated by us via the qrcode helper; safe to inject.
  qr.innerHTML = qrcodeSvg

  wrapper.appendChild(heading)
  wrapper.appendChild(subtitle)
  wrapper.appendChild(qr)
  content.appendChild(wrapper)

  popup.querySelector<HTMLElement>('.nice-popup-close')?.addEventListener('click', (event) => {
    event.stopPropagation()
    hidePopup(popup)
  })

  return popup
}

export function buildSearchPopup(): HTMLElement {
  const { popup, content } = createDialogShell({ sizeClass: 'nice-popup-md' })
  popup.classList.add('global-search-popup')

  const closeBtn = popup.querySelector<HTMLElement>('.nice-popup-close')
  closeBtn?.classList.add('global-search-close')

  const form = document.createElement('form')
  form.className = 'search-dialog text-center p-3 p-md-5'
  form.action = '/search'

  const inputWrapper = document.createElement('div')
  inputWrapper.className = 'mb-3 mb-md-4'

  const input = document.createElement('input')
  input.className = 'form-control form-control-lg text-center'
  input.type = 'text'
  input.name = 'q'
  input.placeholder = '搜索并回车'
  input.required = true
  inputWrapper.appendChild(input)

  const submit = document.createElement('button')
  submit.type = 'submit'
  submit.className = 'btn btn-primary btn-block btn-lg'
  submit.textContent = '搜索'

  form.appendChild(inputWrapper)
  form.appendChild(submit)
  content.appendChild(form)

  return popup
}

export function buildToastPopup(message: string, kind: 'success' | 'error' = 'success'): HTMLElement {
  const popup = document.createElement('div')
  popup.className = `nice-popup nice-popup-center sticky-top ${kind} nice-popup-open${kind === 'error' ? ' nice-popup-error' : ''}`

  const overlay = document.createElement('div')
  overlay.className = 'nice-popup-overlay'

  const body = document.createElement('div')
  body.className = 'nice-popup-body'

  const close = document.createElement('div')
  close.className = 'nice-popup-close'
  const icon = document.createElement('span')
  icon.className = kind === 'error' ? 'svg-dark' : 'svg-white'
  close.appendChild(icon)

  const content = document.createElement('div')
  content.className = 'nice-popup-content'

  if (kind === 'success') {
    const successIcon = document.createElement('div')
    successIcon.className = 'icon success'
    content.appendChild(successIcon)
  } else {
    const errorIcon = document.createElement('div')
    errorIcon.className = 'icon'
    content.appendChild(errorIcon)
  }

  const text = document.createElement('div')
  text.className = 'text-center'
  const p = document.createElement('p')
  p.className = 'mt-1 mb-2'
  // For error messages we may receive HTML (multiple <p> from input issues).
  if (kind === 'error' && /<\w+/.test(message)) {
    p.innerHTML = message // generated server-side with no user content interpolation
  } else {
    p.textContent = message
  }
  text.appendChild(p)
  content.appendChild(text)

  body.appendChild(close)
  body.appendChild(content)
  popup.appendChild(overlay)
  popup.appendChild(body)

  return popup
}
