import { z } from 'zod'

import { c } from './_base'
import { standardMutationErrors, standardReadErrors } from './_errors'

// ─── Schemas ────────────────────────────────────────────

const idParam = z.object({ id: z.string().min(1) })
const userIdBody = z.object({ userId: z.string().min(1) })
const successResponse = z.object({ success: z.boolean() })

// ─── Contract ──────────────────────────────────────────

export const adminContract = c.router(
  {
    addMusic: {
      method: 'POST',
      path: '/admin/add-music',
      body: z.any() /* TODO: use addMusicSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'addMusic',
    },
    approveCommentDeletion: {
      method: 'POST',
      path: '/admin/approve-comment-deletion',
      body: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'approveCommentDeletion',
    },
    bulkApproveUserComments: {
      method: 'POST',
      path: '/admin/bulk-approve-user-comments',
      body: z.any() /* TODO: use userIdSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'bulkApproveUserComments',
    },
    bulkSoftDeleteUserComments: {
      method: 'DELETE',
      path: '/admin/bulk-soft-delete-user-comments',
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'bulkSoftDeleteUserComments',
    },
    clearCache: {
      method: 'POST',
      path: '/admin/clear-cache',
      body: z.any() /* TODO: use clearCacheSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'clearCache',
    },
    deleteCategory: {
      method: 'DELETE',
      path: '/admin/delete-category/:id',
      pathParams: idParam,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'deleteCategory',
    },
    deleteFriend: {
      method: 'DELETE',
      path: '/admin/delete-friend/:id',
      pathParams: idParam,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'deleteFriend',
    },
    deleteImage: {
      method: 'DELETE',
      path: '/admin/delete-image/:id',
      pathParams: idParam,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'deleteImage',
    },
    deleteMusic: {
      method: 'DELETE',
      path: '/admin/delete-music/:id',
      pathParams: idParam,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'deleteMusic',
    },
    deletePage: {
      method: 'DELETE',
      path: '/admin/delete-page/:id',
      pathParams: idParam,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'deletePage',
    },
    deletePost: {
      method: 'DELETE',
      path: '/admin/delete-post/:id',
      pathParams: idParam,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'deletePost',
    },
    deleteTag: {
      method: 'DELETE',
      path: '/admin/delete-tag/:id',
      pathParams: idParam,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'deleteTag',
    },
    getCacheStats: {
      method: 'GET',
      path: '/admin/get-cache-stats/:id',
      pathParams: idParam,
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'getCacheStats',
    },
    getPage: {
      method: 'GET',
      path: '/admin/get-page/:id',
      pathParams: idParam,
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'getPage',
    },
    getPost: {
      method: 'GET',
      path: '/admin/get-post/:id',
      pathParams: idParam,
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'getPost',
    },
    getSettings: {
      method: 'GET',
      path: '/admin/get-settings/:id',
      pathParams: idParam,
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'getSettings',
    },
    getUser: {
      method: 'POST',
      path: '/admin/get-user/:id',
      pathParams: idParam,
      body: z.any() /* TODO: use userIdSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'getUser',
    },
    inviteAuthor: {
      method: 'POST',
      path: '/admin/invite-author',
      body: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'inviteAuthor',
    },
    listCategories: {
      method: 'GET',
      path: '/admin/list-categories',
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'listCategories',
    },
    listFriends: {
      method: 'GET',
      path: '/admin/list-friends',
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'listFriends',
    },
    listImages: {
      method: 'GET',
      path: '/admin/list-images',
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'listImages',
    },
    listMusic: {
      method: 'GET',
      path: '/admin/list-music',
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'listMusic',
    },
    listPageRevisions: {
      method: 'GET',
      path: '/admin/list-page-revisions',
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'listPageRevisions',
    },
    listPages: {
      method: 'GET',
      path: '/admin/list-pages',
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'listPages',
    },
    listPendingDashboard: {
      method: 'GET',
      path: '/admin/list-pending-dashboard',
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'listPendingDashboard',
    },
    listPostRevisions: {
      method: 'GET',
      path: '/admin/list-post-revisions',
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'listPostRevisions',
    },
    listPosts: {
      method: 'GET',
      path: '/admin/list-posts',
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'listPosts',
    },
    listTags: {
      method: 'GET',
      path: '/admin/list-tags',
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'listTags',
    },
    listUsers: {
      method: 'GET',
      path: '/admin/list-users',
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'listUsers',
    },
    muteUser: {
      method: 'PATCH',
      path: '/admin/mute-user/:id',
      pathParams: idParam,
      body: z.any() /* TODO: use muteUserSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'muteUser',
    },
    previewPage: {
      method: 'POST',
      path: '/admin/preview-page',
      body: z.any() /* TODO: use previewPageBodySchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'previewPage',
    },
    previewPost: {
      method: 'POST',
      path: '/admin/preview-post',
      body: z.any() /* TODO: use previewPostBodySchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'previewPost',
    },
    publishLatest: {
      method: 'POST',
      path: '/admin/publish-latest',
      body: z.any() /* TODO: use savePageBodySchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'publishLatest',
    },
    publishPostLatest: {
      method: 'POST',
      path: '/admin/publish-post-latest',
      body: z.any() /* TODO: use savePostBodySchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'publishPostLatest',
    },
    recalculateImageThumbhash: {
      method: 'POST',
      path: '/admin/recalculate-image-thumbhash',
      body: z.any() /* TODO: use recalculateThumbhashSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'recalculateImageThumbhash',
    },
    reindexSearch: {
      method: 'POST',
      path: '/admin/reindex-search',
      body: z.any() /* TODO: use reindexInputSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'reindexSearch',
    },
    renderMath: {
      method: 'POST',
      path: '/admin/render-math',
      body: z.any() /* TODO: use renderMathSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'renderMath',
    },
    renderMermaid: {
      method: 'POST',
      path: '/admin/render-mermaid',
      body: z.any() /* TODO: use renderMermaidSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'renderMermaid',
    },
    reorderCategories: {
      method: 'POST',
      path: '/admin/reorder-categories',
      body: z.any() /* TODO: use reorderCategoriesSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'reorderCategories',
    },
    restorePage: {
      method: 'POST',
      path: '/admin/restore-page/:id',
      pathParams: idParam,
      body: z.any() /* TODO: use restorePageSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'restorePage',
    },
    restorePost: {
      method: 'POST',
      path: '/admin/restore-post/:id',
      pathParams: idParam,
      body: z.any() /* TODO: use restorePostSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'restorePost',
    },
    restoreUser: {
      method: 'POST',
      path: '/admin/restore-user/:id',
      pathParams: idParam,
      body: z.any() /* TODO: use userIdSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'restoreUser',
    },
    revokeSession: {
      method: 'POST',
      path: '/admin/revoke-session',
      body: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'revokeSession',
    },
    revokeUserSessions: {
      method: 'POST',
      path: '/admin/revoke-user-sessions',
      body: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'revokeUserSessions',
    },
    saveDraft: {
      method: 'POST',
      path: '/admin/save-draft',
      body: z.any() /* TODO: use savePageBodySchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'saveDraft',
    },
    savePostDraft: {
      method: 'POST',
      path: '/admin/save-post-draft',
      body: z.any() /* TODO: use savePostBodySchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'savePostDraft',
    },
    searchMusic: {
      method: 'GET',
      path: '/admin/search-music',
      query: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'searchMusic',
    },
    sendPasswordReset: {
      method: 'POST',
      path: '/admin/send-password-reset',
      body: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'sendPasswordReset',
    },
    sendTestMail: {
      method: 'POST',
      path: '/admin/send-test-mail',
      body: z.any() /* TODO: use sendTestMailSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'sendTestMail',
    },
    softDeleteUser: {
      method: 'DELETE',
      path: '/admin/soft-delete-user/:id',
      pathParams: idParam,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'softDeleteUser',
    },
    unpublishPage: {
      method: 'POST',
      path: '/admin/unpublish-page',
      body: z.any() /* TODO: use unpublishPageSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'unpublishPage',
    },
    unpublishPost: {
      method: 'POST',
      path: '/admin/unpublish-post',
      body: z.any() /* TODO: use unpublishPostSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'unpublishPost',
    },
    updateImageNote: {
      method: 'PATCH',
      path: '/admin/update-image-note/:id',
      pathParams: idParam,
      body: z.any() /* TODO: use updateImageNoteSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'updateImageNote',
    },
    updateMusic: {
      method: 'PATCH',
      path: '/admin/update-music/:id',
      pathParams: idParam,
      body: z.any() /* TODO: use updateMusicSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'updateMusic',
    },
    updateSettings: {
      method: 'PATCH',
      path: '/admin/update-settings/:id',
      pathParams: idParam,
      body: z.any() /* TODO: use updateSettingsSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'updateSettings',
    },
    updateUserRole: {
      method: 'POST',
      path: '/admin/update-user-role/:id',
      pathParams: idParam,
      body: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'updateUserRole',
    },
    uploadImage: {
      method: 'POST',
      path: '/admin/upload-image',
      body: z.any(),
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'uploadImage',
    },
    upsertCategory: {
      method: 'POST',
      path: '/admin/upsert-category',
      body: z.any() /* TODO: use upsertCategorySchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'upsertCategory',
    },
    upsertFriend: {
      method: 'POST',
      path: '/admin/upsert-friend',
      body: z.any() /* TODO: use upsertFriendSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'upsertFriend',
    },
    upsertPageMeta: {
      method: 'POST',
      path: '/admin/upsert-page-meta',
      body: z.any() /* TODO: use upsertPageMetaSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'upsertPageMeta',
    },
    upsertPostMeta: {
      method: 'POST',
      path: '/admin/upsert-post-meta',
      body: z.any() /* TODO: use upsertPostMetaSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'upsertPostMeta',
    },
    upsertTag: {
      method: 'POST',
      path: '/admin/upsert-tag',
      body: z.any() /* TODO: use upsertTagSchema */,
      responses: { 200: z.any(), ...standardMutationErrors },
      summary: 'upsertTag',
    },
  },
  { strictStatusCodes: true },
)
