-- Add `page.show_friends` — meta toggle that, when true, renders
-- the global friends grid at the bottom of the page detail route
-- (the same grid the legacy `<Friends />` MDX component rendered).
--
-- DEFAULT false because most pages opt out (the `links` page is the
-- canonical opt-in). The column is `NOT NULL` so the application
-- code can read it as a plain `boolean` without a null guard.
--
-- Wrapped in a single statement (Postgres `ADD COLUMN` is implicitly
-- atomic at the DDL level), no `DO $$ … $$` needed since there is
-- only one statement and `IF NOT EXISTS` keeps it idempotent for
-- repeat runs.
ALTER TABLE "page" ADD COLUMN IF NOT EXISTS "show_friends" boolean NOT NULL DEFAULT false;
