export type ApiActionMethod = 'GET' | 'POST' | 'PATCH' | 'DELETE'

// API endpoint descriptors. Paths point to Hono + ts-rest endpoints.
// Old `/api/actions/*` URLs receive 308 redirects from the Hono entry.
function defineApiAction(path: string, method: ApiActionMethod) {
  return { path, method } as const
}

export const API_ACTIONS = {
  account: {
    updateProfile: defineApiAction('/api/account/profile', 'PATCH'),
    updatePassword: defineApiAction('/api/account/password', 'POST'),
    revokeSession: defineApiAction('/api/account/sessions/revoke', 'POST'),
  },
  auth: {
    updateUser: defineApiAction('/api/auth/users', 'PATCH'),
  },
  comment: {
    increaseLike: defineApiAction('/api/comment/likes', 'POST'),
    decreaseLike: defineApiAction('/api/comment/likes', 'DELETE'),
    validateLikeToken: defineApiAction('/api/comment/likes/validate', 'POST'),
    findAvatar: defineApiAction('/api/comment/avatar', 'POST'),
    replyComment: defineApiAction('/api/comment/comments', 'POST'),
    approve: defineApiAction('/api/admin/comments/approve', 'PATCH'),
    delete: defineApiAction('/api/admin/comments/delete', 'DELETE'),
    loadComments: defineApiAction('/api/comment/comments', 'GET'),
    getRaw: defineApiAction('/api/admin/comments/raw', 'GET'),
    edit: defineApiAction('/api/comment/comments/:rid', 'PATCH'),
    myComments: defineApiAction('/api/comment/my', 'GET'),
    revokeToken: defineApiAction('/api/comment/tokens/revoke', 'POST'),
    searchPages: defineApiAction('/api/admin/comments/search-pages', 'GET'),
    searchAuthors: defineApiAction('/api/admin/comments/search-authors', 'GET'),
    loadAll: defineApiAction('/api/admin/comments/all', 'POST'),
    updateOwn: defineApiAction('/api/comment/own', 'POST'),
    requestDeleteOwn: defineApiAction('/api/comment/own/delete', 'POST'),
    cancelDeleteOwn: defineApiAction('/api/comment/own/delete', 'DELETE'),
    listMine: defineApiAction('/api/comment/my', 'GET'),
  },
  image: {
    resolveThumbhash: defineApiAction('/api/image/thumbhash', 'GET'),
  },
  music: {
    get: defineApiAction('/api/music', 'GET'),
  },
  admin: {
    listUsers: defineApiAction('/api/admin/users', 'GET'),
    getUser: defineApiAction('/api/admin/users', 'GET'),
    softDeleteUser: defineApiAction('/api/admin/users', 'DELETE'),
    restoreUser: defineApiAction('/api/admin/users/restore', 'POST'),
    muteUser: defineApiAction('/api/admin/users/mute', 'PATCH'),
    bulkApproveUserComments: defineApiAction('/api/admin/comments/bulk-approve', 'POST'),
    bulkSoftDeleteUserComments: defineApiAction('/api/admin/comments/bulk-delete', 'DELETE'),
    getSettings: defineApiAction('/api/admin/settings', 'GET'),
    updateSettings: defineApiAction('/api/admin/settings', 'PATCH'),
    getCacheStats: defineApiAction('/api/admin/cache/stats', 'GET'),
    clearCache: defineApiAction('/api/admin/cache/clear', 'POST'),
    sendTestMail: defineApiAction('/api/admin/mail/test', 'POST'),
    listFriends: defineApiAction('/api/admin/friends', 'GET'),
    upsertFriend: defineApiAction('/api/admin/friends', 'POST'),
    deleteFriend: defineApiAction('/api/admin/friends', 'DELETE'),
    listCategories: defineApiAction('/api/admin/categories', 'GET'),
    upsertCategory: defineApiAction('/api/admin/categories', 'POST'),
    deleteCategory: defineApiAction('/api/admin/categories', 'DELETE'),
    reorderCategories: defineApiAction('/api/admin/categories/reorder', 'POST'),
    listTags: defineApiAction('/api/admin/tags', 'GET'),
    upsertTag: defineApiAction('/api/admin/tags', 'POST'),
    deleteTag: defineApiAction('/api/admin/tags', 'DELETE'),
    listImages: defineApiAction('/api/admin/images', 'GET'),
    uploadImage: defineApiAction('/api/admin/images/upload', 'POST'),
    deleteImage: defineApiAction('/api/admin/images', 'DELETE'),
    updateImageNote: defineApiAction('/api/admin/images/note', 'PATCH'),
    recalculateImageThumbhash: defineApiAction('/api/admin/images/thumbhash', 'POST'),
    listMusic: defineApiAction('/api/admin/music', 'GET'),
    searchMusic: defineApiAction('/api/admin/music/search', 'GET'),
    addMusic: defineApiAction('/api/admin/music', 'POST'),
    updateMusic: defineApiAction('/api/admin/music', 'PATCH'),
    deleteMusic: defineApiAction('/api/admin/music', 'DELETE'),
    listPages: defineApiAction('/api/admin/pages', 'GET'),
    getPage: defineApiAction('/api/admin/pages', 'GET'),
    upsertPageMeta: defineApiAction('/api/admin/pages/meta', 'POST'),
    deletePage: defineApiAction('/api/admin/pages', 'DELETE'),
    restorePage: defineApiAction('/api/admin/pages/restore', 'POST'),
    listPageRevisions: defineApiAction('/api/admin/pages/revisions', 'GET'),
    saveDraft: defineApiAction('/api/admin/pages/drafts', 'POST'),
    publishLatest: defineApiAction('/api/admin/pages/publish', 'POST'),
    unpublishPage: defineApiAction('/api/admin/pages/unpublish', 'POST'),
    previewPage: defineApiAction('/api/admin/pages/preview', 'POST'),
    listPosts: defineApiAction('/api/admin/posts', 'GET'),
    getPost: defineApiAction('/api/admin/posts', 'GET'),
    upsertPostMeta: defineApiAction('/api/admin/posts/meta', 'POST'),
    deletePost: defineApiAction('/api/admin/posts', 'DELETE'),
    restorePost: defineApiAction('/api/admin/posts/restore', 'POST'),
    listPostRevisions: defineApiAction('/api/admin/posts/revisions', 'GET'),
    savePostDraft: defineApiAction('/api/admin/posts/drafts', 'POST'),
    publishPostLatest: defineApiAction('/api/admin/posts/publish', 'POST'),
    unpublishPost: defineApiAction('/api/admin/posts/unpublish', 'POST'),
    previewPost: defineApiAction('/api/admin/posts/preview', 'POST'),
    renderMath: defineApiAction('/api/admin/editor/render-math', 'POST'),
    renderMermaid: defineApiAction('/api/admin/editor/render-mermaid', 'POST'),
    reindexSearch: defineApiAction('/api/admin/search/reindex', 'POST'),
    approveCommentDeletion: defineApiAction('/api/admin/comments/approve-deletion', 'POST'),
    listPendingDashboard: defineApiAction('/api/admin/dashboard/pending', 'GET'),
    inviteAuthor: defineApiAction('/api/admin/users/invite', 'POST'),
    updateUserRole: defineApiAction('/api/admin/users/role', 'POST'),
    sendPasswordReset: defineApiAction('/api/admin/users/password-reset', 'POST'),
    revokeSession: defineApiAction('/api/admin/users/sessions/revoke', 'POST'),
    revokeUserSessions: defineApiAction('/api/admin/users/sessions/revoke-all', 'POST'),
  },
  analytics: {
    counters: defineApiAction('/api/analytics/counters', 'GET'),
    views: defineApiAction('/api/analytics/views', 'GET'),
    heatmap: defineApiAction('/api/analytics/heatmap', 'GET'),
    metrics: defineApiAction('/api/analytics/metrics', 'GET'),
  },
} as const
