// Type-safe client for the `apiContract` tree.
//
// Generated by `initClient` — every call site reads as
// `api.<domain>.<endpoint>({ params, query, body })` and gets back
// a discriminated union `{ status, body }` whose `body` is
// typed exactly to that status's schema. Use `unwrap` from
// `./unwrap` to drop the success branch and throw `ApiError` on 4xx.
//
// `apiContract` ships the Zod schemas into the client bundle. Per
// migration plan Part 7.1: total estimated cost is < 50KB gzipped
// once all 92 endpoints are migrated; first-version we monitor and
// only split into public/admin contracts if the budget is exceeded.

import { initClient } from '@ts-rest/core'

import { apiContract } from '@/shared/contracts'

export const api = initClient(apiContract, {
  baseUrl: '',
  baseHeaders: {
    'Content-Type': 'application/json',
  },
})

export type ApiClient = typeof api
