// Display labels for the `language-*` class that lands on `<pre>` /
// `<code>` after Shiki / Markdown pre-render. Used by `CodeBlock` to
// render the small badge in the code chrome. Living in `@/ui/lib` so
// the 4KB map doesn't bloat the component file (it's data, not view).
//
// Keep entries lowercase — `LANGUAGE_CLASS` in CodeBlock.tsx is the
// `/i` regex that extracts the raw identifier; we normalise to lower
// before the lookup so a user-typed `language-TypeScript` still
// matches `ts` / `typescript`.
export const LANGUAGE_MAP: Record<string, string> = {
  html: 'HTML',
  htm: 'HTML',
  xhtml: 'XHTML',
  xml: 'XML',
  svg: 'SVG',
  css: 'CSS',
  scss: 'SCSS (Sass)',
  sass: 'Sass',
  less: 'Less',
  js: 'JavaScript',
  jsx: 'JSX',
  ts: 'TypeScript',
  tsx: 'TSX',
  vue: 'Vue',
  svelte: 'Svelte',
  astro: 'Astro',
  json: 'JSON',
  jsonc: 'JSON with Comments',
  yaml: 'YAML',
  yml: 'YAML',
  toml: 'TOML',
  ini: 'INI',
  env: 'Environment Variables',
  py: 'Python',
  rb: 'Ruby',
  php: 'PHP',
  java: 'Java',
  kotlin: 'Kotlin',
  swift: 'Swift',
  cpp: 'C++',
  cc: 'C++',
  cxx: 'C++',
  c: 'C',
  cs: 'C#',
  go: 'Go',
  rs: 'Rust',
  dart: 'Dart',
  scala: 'Scala',
  groovy: 'Groovy',
  perl: 'Perl',
  pl: 'Perl',
  lua: 'Lua',
  r: 'R',
  julia: 'Julia',
  zig: 'Zig',
  sh: 'Shell',
  bash: 'Bash',
  zsh: 'Zsh',
  fish: 'Fish Shell',
  ps1: 'PowerShell',
  bat: 'Batchfile',
  cmd: 'Windows Command Script',
  dockerfile: 'Dockerfile',
  makefile: 'Makefile',
  cmake: 'CMake',
  awk: 'Awk',
  sed: 'Sed',
  sql: 'SQL',
  mysql: 'MySQL',
  postgres: 'PostgreSQL',
  plsql: 'PL/SQL',
  graphql: 'GraphQL',
  gql: 'GraphQL',
  cypher: 'Cypher (Neo4j)',
  influxql: 'InfluxQL',
  csv: 'CSV',
  tsv: 'TSV',
  parquet: 'Parquet',
  avro: 'Avro',
  terraform: 'Terraform',
  tf: 'Terraform',
  hcl: 'HCL (HashiCorp Configuration Language)',
  ansible: 'Ansible',
  puppet: 'Puppet',
  chef: 'Chef',
  k8s: 'Kubernetes YAML',
  helm: 'Helm Chart',
  nginx: 'Nginx Config',
  apache: 'Apache Config',
  conf: 'Config File',
  md: 'Markdown',
  mdx: 'MDX',
  rst: 'reStructuredText',
  asciidoc: 'AsciiDoc',
  plaintext: 'Plain Text',
  txt: 'Plain Text',
  log: 'Log File',
  ejs: 'EJS',
  pug: 'Pug (Jade)',
  mustache: 'Mustache',
  handlebars: 'Handlebars',
  hbs: 'Handlebars',
  jinja: 'Jinja2',
  erb: 'ERB (Embedded Ruby)',
  liquid: 'Liquid',
  hs: 'Haskell',
  ml: 'OCaml/Standard ML',
  elm: 'Elm',
  clj: 'Clojure',
  cljs: 'ClojureScript',
  lisp: 'Lisp',
  scheme: 'Scheme',
  prolog: 'Prolog',
  asm: 'Assembly',
  nasm: 'NASM Assembly',
  vhdl: 'VHDL',
  verilog: 'Verilog',
  gdscript: 'GDScript',
  glsl: 'GLSL',
  hlsl: 'HLSL',
  shader: 'Shader',
  unity: 'Unity C#',
  ipynb: 'Jupyter Notebook',
  rmd: 'R Markdown',
  diff: 'Diff',
  patch: 'Patch',
  regex: 'Regular Expression',
  http: 'HTTP',
  rest: 'REST Client',
  dockerignore: 'Docker Ignore',
  gitignore: 'Git Ignore',
  gitattributes: 'Git Attributes',
  editorconfig: 'EditorConfig',
}
