export type {
  AdminListFilters,
  AdminPendingKind,
  AdminPendingRow,
  CommentAuthor,
  CommentWithUser,
  EntitySlugTitle,
  MyCommentEntity,
  MyCommentsFilters,
  MyCommentsStatus,
  PageOption,
  ParentCommentRow,
  PendingCommentRow,
} from '@/server/infra/db/operations/comment'

export {
  adminClearDeleteRequest,
  adminUserIds,
  approveCommentById,
  bulkApprovePendingByUser,
  bulkSoftDeleteCommentsByUser,
  commentsByIds,
  countAdminPendingDashboard,
  countAllComments,
  countApprovedCommentsByUser,
  countApprovedRepliesOfComment,
  countCommentsAndRoots,
  countMyComments,
  deleteCommentById,
  findChildComments,
  findCommentRootId,
  findCommentsByIds,
  findRootComments,
  findCommentWithSourceUser,
  findCommentWithUserAndTarget,
  findCommentWithUserById,
  findParentCommentsByIds,
  insertComment,
  latestDistinctCommentIds,
  listAdminComments,
  listAdminPendingDashboard,
  listMyCommentEntities,
  listMyComments,
  pendingComments,
  recentCommentsForUserDedupe,
  clearDeleteRequest,
  requestDeleteComment,
  resolveEntitiesForComments,
  searchCommentAuthors,
  searchPages,
  softDeleteCommentById,
  updateCommentBodyAndContent,
  updateCommentContent,
  updateOwnCommentBody,
  updateOwnCommentBodyAndPending,
} from '@/server/infra/db/operations/comment'
