import { type RouteConfig, index, route } from '@react-router/dev/routes'

export default [
  index('routes/home.tsx'),
  route('page/:num', 'routes/home-page.tsx'),
  route('archives', 'routes/archives.tsx'),
  route('categories', 'routes/categories.tsx'),
  route('tags', 'routes/tags-index.tsx'),
  route('feed', 'routes/feed-rss.ts'),
  route('feed/atom', 'routes/feed-atom.ts'),
  route('cats/:slug', 'routes/category-list.tsx'),
  route('cats/:slug/feed', 'routes/category-feed-rss.ts'),
  route('cats/:slug/feed/atom', 'routes/category-feed-atom.ts'),
  route('cats/:slug/page/:num', 'routes/category-list-page.tsx'),
  route('tags/:slug', 'routes/tag-list.tsx'),
  route('tags/:slug/feed', 'routes/tag-feed-rss.ts'),
  route('tags/:slug/feed/atom', 'routes/tag-feed-atom.ts'),
  route('tags/:slug/page/:num', 'routes/tag-list-page.tsx'),
  route('search', 'routes/search-index.tsx'),
  route('search/:keyword', 'routes/search-list.tsx'),
  route('search/:keyword/page/:num', 'routes/search-list-page.tsx'),
  route('sitemap.xml', 'routes/sitemap.ts'),
  route('images/og/:slug.png', 'routes/image-og.ts'),
  route('images/calendar/:year/:time.png', 'routes/image-calendar.ts'),
  route('images/avatar/:hash.png', 'routes/image-avatar.ts'),
  route('api/actions/:domain/:name', 'routes/api-action.tsx'),
  route('wp-login.php', 'routes/wp-login.tsx'),
  route('wp-admin', 'routes/wp-admin.tsx'),
  route('wp-admin/install.php', 'routes/wp-admin-install.tsx'),
  route('posts/:slug', 'routes/post-detail.tsx'),
  route(':slug', 'routes/page-detail.tsx'),
] satisfies RouteConfig
